apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260531-145115-80pdx5l5jxrg-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260531-145115-80pdx5l5jxrg.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260531-145115-80pdx5l5jxrg-service
            port:
              number: 80
