apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260531-145115-80pdx5l5jxrg-service
spec:
  selector:
    app: enterprise-system-20260531-145115-80pdx5l5jxrg
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
